### ISSUE TITLE
ClearML: failure in set_memory_growth()

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#102]
When launching a ClearML [experiment ](https://app.pro.clear.ml/projects/7868968295f94e13911ce7bbfa25acd2/experiments/c0fc0324ad4444fca9c73b6c4de5c570/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=status:failed) with the _memory_growth_ option set to True on the _langtech_20gb_ queue, the experiment will frequently fail at the start of training with the error:  `RuntimeError: Physical devices cannot be modified after being initialized`.

The same experiment trains successfully if it is launched with _memory_growth_ set to False.

**Experiment Launch Configuration:**
```
exp = SILExperimentCML(
    name="BT-Korean/AE.ja-ko.oro-ko.2",
    make_stats=True,  # limited by stats_max_size to process only Bibles
    mixed_precision=True,  # clearML GPU's can handle mixed precision
    memory_growth=True,
    queue_name="langtech_20gb",
    remote_execution=True,
)
```

**Stack Trace:**

`Traceback (most recent call last):
  File "scratchpad_s3.py", line 11, in <module>
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 29, in run
    self.train()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 41, in train
    runner = create_runner(self.config, mixed_precision=self.mixed_precision, memory_growth=self.memory_growth)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 1673, in create_runner
    tf.config.experimental.set_memory_growth(device, enable=True)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/framework/config.py", line 594, in set_memory_growth
    context.context().set_memory_growth(device, enable)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 1448, in set_memory_growth
    raise RuntimeError(
RuntimeError: Physical devices cannot be modified after being initialized`

**Comment by ddaspit** [comment]
This is probably happening because we call `create_runner` during preprocessing (see `Config._update_vocab()` without enabling memory growth and then we call `create_runner` again during training, this time with memory growth enabled.

**Comment by johnml1135** [comment]
Yeah, that looks right.  I'll try my hand at fixing it.

**Comment by ddaspit** [comment]
@johnml1135 Has this been fixed? If so, please close this issue.
