### ISSUE TITLE
'Blas GEMM launch failed' when training child model on ClearML langtech_10gb queue

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#103]
When training a child model on the _langtech_10gb_ queue, the [experiment ](https://app.pro.clear.ml/projects/7868968295f94e13911ce7bbfa25acd2/experiments/d8adc6e31d684685b59e1aa06979fee2/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=status:failed) will frequently fail during preprocessing.  It appears to be failing during the conversion of the parent model checkpoint.

**Stack trace:**
`
INFO:tensorflow:Restored checkpoint /tmp/tmpmjedak3y/BT-Korean/Base/run/export/55000/ckpt
2021-11-02 21:01:36.642294: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-11-02 21:01:37.916032: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-11-02 21:01:37.922798: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-11-02 21:01:37.926048: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-11-02 21:01:37.926059: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "scratchpad_s3.py", line 11, in <module>
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 28, in run
    self.preprocess()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 34, in preprocess
    self.config.preprocess(self.make_stats)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 670, in preprocess
    self._build_vocabs()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 1484, in _build_vocabs
    self._update_vocab(self.exp_dir / "src-onmt.vocab", self.exp_dir / "trg-onmt.vocab")
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 1499, in _update_vocab
    parent_runner.update_vocab(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/runner.py", line 269, in update_vocab
    model.create_variables(optimizer=optimizer)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/models/model.py", line 424, in create_variables
    _ = self(features, labels=labels, training=True, step=0)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/models/model.py", line 102, in __call__
    outputs, predictions = super().__call__(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/models/sequence_to_sequence.py", line 160, in call
    encoder_outputs, encoder_state, encoder_sequence_length = self.encoder(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/encoders/encoder.py", line 56, in __call__
    outputs, state, sequence_length = super().__call__(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/encoders/self_attention_encoder.py", line 82, in call
    inputs = layer(inputs, mask=mask, training=training)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/layers/transformer.py", line 477, in call
    y, _ = self.self_attention(x, mask=mask, training=training)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/layers/common.py", line 131, in call
    all_outputs = self.layer(x, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/layers/transformer.py", line 308, in call
    queries = self.linear_queries(inputs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/layers/common.py", line 65, in call
    outputs = tf.matmul(inputs, self.kernel, transpose_b=self.transpose)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 3314, in matmul
    return gen_math_ops.mat_mul(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5532, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(1, 512), b.shape=(512, 512), m=1, n=512, k=512 [Op:MatMul]`

**Comment by ddaspit** [comment]
@johnml1135 Has this been fixed? If so, please close this issue.
