### ISSUE TITLE
AQUA/S3 - Path error building vocabulary with Key Biblical Terms list

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#106]
When building the target vocabulary for the BCH / BCHVE Bible pairing on the AQUA server using the S3 storage (experiment [link](https://app.pro.clear.ml/projects/ef6ca3f989104b72a9a259167312caab/experiments/89d88fb596484fe1a4f62280025e69c4/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update)), the target vocab building fails with the following error:

```
Traceback (most recent call last):
  File "scratchpad_s3.py", line 12, in <module>
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 35, in run
    self.preprocess()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 41, in preprocess
    self.config.preprocess(self.make_stats)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 684, in preprocess
    self._build_vocabs()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 1496, in _build_vocabs
    self._create_unshared_vocab(self.trg_isos, trg_vocab_file_paths, "target")
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 1572, in _create_unshared_vocab
    build_vocab(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/config.py", line 394, in build_vocab
    file_paths.sort()
TypeError: '<' not supported between instances of 'PosixPath' and 'S3Path'
```

The error occurs when the Bible pair is used standalone and when it is used with a parent model.  It appears to be related to pulling the KBT's into the target side vocabulary for SentencePiece.

**Comment by johnml1135** [comment]
Does this fix it?
