### ISSUE TITLE
Translate is trying to use ClearML even though it was not requested. Preventing translation on local machine.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#109]
I tried to translate with the following command line and trace.
The command is meant to run locally, but there is an error about ClearML credentials. The ClearML argument was not set in the command line.

```
python -m silnlp.nmt.translate --checkpoint 6000 --src-project GELA3_2021_11_22 --book OT --trg-iso en  nlg-en-4
2021-11-22 12:53:27.859063: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-11-22 12:53:30,996 - silnlp.common.environment - INFO - Using workspace: /home/david/Gutenberg_new as per environment variable SIL_NLP_DATA_PATH.
2021-11-22 12:53:31,372 - silnlp.common.utils - INFO - Git commit: 12aca87cab
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 181, in <module>
    main()
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 169, in main
    translator.translate_book(
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 82, in translate_book
    self.init_translation_task(experiment_suffix=f"_{self.checkpoint}_{book}")
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 57, in init_translation_task
    self.clearml = SILClearML(
  File "<string>", line 8, in __init__
  File "/home/david/silnlp/silnlp/common/clearml.py", line 27, in __post_init__
    self.task = Task.init(
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/task.py", line 491, in init
    task = cls._create_dev_task(
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/task.py", line 2554, in _create_dev_task
    task = cls(
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/task.py", line 164, in __init__
    super(Task, self).__init__(**kwargs)
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_interface/task/task.py", line 151, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 131, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 34, in __init__
    self._session = session or self._get_default_session()
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 101, in _get_default_session
    InterfaceBase._default_session = Session(
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 198, in __init__
    self.refresh_token()
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_api/session/token_manager.py", line 104, in refresh_token
    self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 713, in _do_refresh_token
    six.reraise(*sys.exc_info())
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/david/.cache/pypoetry/virtualenvs/silnlp-gt_VMn9E-py3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 699, in _do_refresh_token
    raise LoginError(
clearml.backend_api.session.session.LoginError: Failed getting token (error 401 from https://api.pro.clear.ml): Unauthorized (invalid credentials) (failed to locate provided credentials)
david@pop-os:~/silnlp$ 
```

**Comment by johnml1135** [comment]
Did that fix it?

**Comment by davidbaines** [comment]
Yes! Thanks so much.
