### ISSUE TITLE
Guided alignment with non-Scripture corpora - val.vref.txt does not exist

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#115]
For an AlignmentEnhanced model with only non-Scriptural corpora, there is no val.vref.txt file created.  The new guided alignment logic expects this file to be available during the validation step of training.  Validation fails with the error:

```
INFO:tensorflow:Saved checkpoint /tmp/tmpmgoqv71s/BT-Korean/AE.en-ko.CCMatrix/run/ckpt-5000
INFO:tensorflow:Running evaluation for step 5000
Traceback (most recent call last):
  File "scratchpad_s3.py", line 14, in <module>
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 37, in run
    self.train()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 58, in train
    runner.train(num_devices=self.num_devices, with_eval=True, checkpoint_path=checkpoint_path)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/runner.py", line 276, in train
    summary = trainer(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/training.py", line 134, in __call__
    early_stop = self._evaluate(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/training.py", line 192, in _evaluate
    evaluator(step)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/evaluation.py", line 318, in __call__
    for source, target in self._dataset:
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 783, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2845, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/tmpmgoqv71s/BT-Korean/AE.en-ko.CCMatrix/val.vref.txt; No such file or directory [Op:IteratorGetNext] 
```

**Comment by mmartin9684-sil** [comment]
A configuration with a mix of Scripture and non-Scripture corpora (example below) also [fails](https://app.pro.clear.ml/projects/7868968295f94e13911ce7bbfa25acd2/experiments/e0095c4fe9914ccd866ae544b8593c59/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update) when running the validation step during training.  See stack trace below.

```
  corpus_pairs:
  - src: en-CCMatrix_en_ko
    trg: ko-CCMatrix_en_ko
    trg_size: 3000
    type: train,val,test
    val_size: 3000
  - src: en-LSV
    test_size: 250
    trg: ko-RNKSV
    type: train,val,test
    val_size: 250
```

```
2021-12-14 22:08:01.261690: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 1 of dimension 0 out of bounds.
2021-12-14 22:08:01.261832: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : 
   ...
2021-12-14 22:08:01.272963: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 1 of dimension 0 out of bounds.
2021-12-14 22:08:36
Traceback (most recent call last):
  File "scratchpad_s3.py", line 14, in <module>
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 37, in run
    self.train()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 58, in train
    runner.train(num_devices=self.num_devices, with_eval=True, checkpoint_path=checkpoint_path)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/runner.py", line 276, in train
    summary = trainer(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/training.py", line 134, in __call__
    early_stop = self._evaluate(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/training.py", line 192, in _evaluate
    evaluator(step)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/opennmt/evaluation.py", line 318, in __call__
    for source, target in self._dataset:
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 783, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2845, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 1 of dimension 0 out of bounds.
	 [[{{node strided_slice_1}}]] [Op:IteratorGetNext]
```
