### ISSUE TITLE
Execute translate script without creating ClearML task

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#120]
Currently, the `silnlp.nmt.translate` script always creates a ClearML task. This should be optional. By default, it should just execute locally.

**Comment by davidbaines** [comment]
I think that this error might be preventing me from using the Translate script locally.

When I try I get the following error:
Installing the current project: silnlp (1.0.0)
(silnlp-gt_VMn9E-py3.8) david@pop-os:~/silnlp$ python -m silnlp.nmt.translate BT-English/cba-en/cba-en_cp01 --src-project cba --trg-iso en --books EXO --output-usfm BT-English/cba-en/cba-en_cp01/02EXOcbaNT --checkpoint best
2022-06-28 21:02:08,808 - silnlp.common.environment - INFO - Using workspace: /home/david/disk2/gutenberg as per environment variable SIL_NLP_DATA_PATH.
2022-06-28 21:02:09,149 - silnlp.common.utils - INFO - Git commit: f46a63c3b3
Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97e4556fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /auth.login
Retrying (Retry(total=238, connect=238, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97e4569190>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /auth.login
^CRetrying (Retry(total=237, connect=237, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97e4569340>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /auth.login

print(args):
Namespace(books=['EXO'], checkpoint='best', clearml_queue=None, eager_execution=False, end_seq=None, experiment='BT-English/cba-en/cba-en_cp01', memory_growth=False, output_usfm='BT-English/cba-en/cba-en_cp01/02EXOcbaNT', src=None, src_prefix=None, src_project='cbaNT', start_seq=None, trg=None, trg_iso='en', trg_prefix=None)

**Comment by davidbaines** [comment]
Tested this for translating and it worked fine.

**Comment by davidbaines** [comment]
(silnlp-gt_VMn9E-py3.8) david@pop-os:~/silnlp$ python -m silnlp.nmt.translate --checkpoint last --src-project tl-TCB --src /home/david/disk2/gutenberg/Paratext/projects/TCB/091SAtlASD15.SFM --trg-iso blx --output-usfm /home/david/disk2/gutenberg/BT-Tagalog/to_blx/tl_blx_uni_dup_share_preserve/results/091SAAMIU_last.sfm BT-Tagalog/to_blx/tl_blx_uni_dup_share_preserve
2022-07-16 15:03:40,452 - silnlp.common.environment - INFO - Using workspace: /home/david/disk2/gutenberg as per environment variable SIL_NLP_DATA_PATH.
2022-07-16 15:03:40,828 - silnlp.common.utils - INFO - Git commit: 8cd5b9c649
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 231, in <module>
    main()
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 225, in main
    translator.translate_text_file(args.src, args.trg_iso, args.trg)
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 151, in translate_text_file
    self.init_translation_task(experiment_suffix=f"_{self.checkpoint}_{os.path.basename(src_file_path)}")
  File "/home/david/silnlp/silnlp/nmt/translate.py", line 79, in init_translation_task
    self.clearml = SILClearML(
  File "<string>", line 9, in __init__
  File "/home/david/silnlp/silnlp/common/clearml_connection.py", line 24, in __post_init__
    self.name = self.name.replace("\\", "/")
AttributeError: 'NoneType' object has no attribute 'replace'
