### ISSUE TITLE
When an SFM file fails to parse report the full file path and if possible the line number.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#149]
Provide a note of which file and line number if applicable when there is an error extracting an SFM file fails to parse.

```F:\GitHub\silnlp>poetry run python -m silnlp.common.extract_corpora <project> 
2023-01-26 16:56:17,910 - silnlp.common.environment - INFO - Using workspace: S: as per environment variable SIL_NLP_DATA_PATH.
2023-01-26 16:56:17,940 - silnlp.common.extract_corpora - INFO - Extracting <project>
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\GitHub\silnlp\silnlp\common\extract_corpora.py", line 103, in <module>
    main()
  File "F:\GitHub\silnlp\silnlp\common\extract_corpora.py", line 77, in main
    corpus_filename, verse_count = extract_project(
  File "F:\GitHub\silnlp\silnlp\common\paratext.py", line 72, in extract_project
    project_corpus = ParatextTextCorpus(project_dir, include_markers=include_markers)
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\machine\corpora\paratext_text_corpus.py", line 67, in __init__
    texts. Append(UsfmFileText(stylesheet, encoding, sfm_filename, versification, include_markers))
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\machine\corpora\usfm_file_text.py", line 21, in __init__
    super().__init__(_get_id(filename, encoding), stylesheet, encoding, versification, include_markers)
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\machine\corpora\usfm_file_text.py", line 39, in _get_id
    raise RuntimeError("The USFM does not contain and 'id' marker.")
RuntimeError: The USFM does not contain and 'id' marker.```

**Comment by ddaspit** [comment]
This will probably require updating the exception thrown by Machine.py to provide more specific information about the line number where the parsing error occurred.
