### ISSUE TITLE
Fix error that prevents translation on Colab.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#168]
I created a colab notebook that successfully fine-tuned an NLLB model with SILNLP.
https://colab.research.google.com/drive/1XcZfChjNBqQiP4exspbpKHX9urglnUE2#scrollTo=TtJdkc8bx7S9

There's an error when I try to translate with the model though. That affects the test also.
```Using python3.8 (3.8.10)
2023-06-15 16:48:50,308 - silnlp.common.environment - INFO - Using workspace: /content/drive/Shareddrives/Gutenberg as per environment variable SIL_NLP_DATA_PATH.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
2023-06-15 16:48:52,377 - silnlp.common.utils - INFO - Git commit: fa63d1416b
2023-06-15 16:48:52,388 - silnlp.nmt.clearml_connection - INFO - No ClearML task initiated.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/silnlp/silnlp/nmt/translate.py", line 278, in <module>
    main()
  File "/content/silnlp/silnlp/nmt/translate.py", line 255, in main
    translator.translate_books(args.books, args.src_project, args.trg_iso)
  File "/content/silnlp/silnlp/nmt/translate.py", line 49, in translate_books
    translator, config, step_str = self._init_translation_task(experiment_suffix=f"_{self. Checkpoint}_{books}")
  File "/content/silnlp/silnlp/nmt/translate.py", line 189, in _init_translation_task
    checkpoint_path, step = model.get_checkpoint_path(self. Checkpoint)
  File "/content/silnlp/silnlp/nmt/hugging_face_config.py", line 688, in get_checkpoint_path
    step = int(ckpt.name[11:])
ValueError: invalid literal for int() with base 10: ''```

**Comment by mshannon-sil** [comment]
@davidbaines I noticed and fixed this issue earlier, but it's in a different branch as part of a set of changes that aren't quite ready to be pull requested into master yet. So I've made a different branch with just the change that fixes this issue, and I've submitted a pull request so that you can review it and merge it into master.

**Comment by davidbaines** [comment]
I cloned this branch in Colab and it translated the books!  Brilliant, thanks so much Matthew.

**Comment by mshannon-sil** [comment]
Great! It's now merged into master.
