### ISSUE TITLE
SIL Machine not working with S3

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#17]
While running silnlp.common.extract_corpora, I got an open file error in the dotnet library.  I think I passed it a file handle, but I may have passed it a path...

``` python
$ python -m silnlp.common.extract_corpora BCH_2021_04_20
2021-05-04 18:55:23,864 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-05-04 18:55:23,995 - silnlp.common.environment - INFO - data path is s3://aqua-ml-data
ClearML Task: created new task id=27655dc5471d4a26998f037d06a05812
ClearML results page: https://app.pro.clear.ml/projects/4df8305e85f2464fae11b9ac5b54cb07/experiments/27655dc5471d4a26998f037d06a05812/output/log
Extracting BCH_2021_04_20...
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\aqua-ml-data\Paratext\projects\Ref\Settings.xml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at SIL.Machine.Corpora.ParatextTextCorpus..ctor(ITokenizer`3 wordTokenizer, String projectDir, Boolean includeMarkers) in C:\projects\machine\src\SIL.Machine\Corpora\ParatextTextCorpus.cs:line 13
   at SIL.Machine.ToolHelpers.CreateTextCorpus(ITokenizer`3 wordTokenizer, String type, String path) in C:\projects\machine\src\SIL.Machine.Tool\ToolHelpers.cs:line 56
   at SIL.Machine.ParallelCorpusCommandSpec.Validate(TextWriter outWriter) in C:\projects\machine\src\SIL.Machine.Tool\ParallelCorpusCommandSpec.cs:line 97
   at SIL.Machine.CommandBase.ExecuteCommand() in C:\projects\machine\src\SIL.Machine.Tool\CommandBase.cs:line 19
   at SIL.Machine.BuildCorpusCommand.ExecuteCommand() in C:\projects\machine\src\SIL.Machine.Tool\BuildCorpusCommand.cs:line 52
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at SIL.Machine.Program.Main(String[] args) in C:\projects\machine\src\SIL.Machine.Tool\Program.cs:line 9
```

**Comment by johnml1135** [comment]
We will not do this.  Short term: mount the S3 bucket or Google Drive as a network drive.  Pass through to Docker.
