### ISSUE TITLE
Failure to run ClearML Experiment (Process failed, exit code 1 / AWS Access Key)

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/silnlp#175]
I received this error 3 times in a row this morning on both idx_40gb and langtech_40gb, both of which were previously idle. This was the only experiment I ran today and it has hit this error each time so far. 

I have seen the `Process failed, exit code 1` message before, but do not recall seeing the preceding AWS access key id error. My local AWS credentials seem to be working fine; I can read and write to the drive and run local steps like preprocessing. 

All the dependencies installed and the environment setup was complete; then if failed. Here is the end of the log. 

```
Environment setup completed successfully
Starting Task Execution:
2023-07-06 16:32:39,417 - silnlp.common.environment - INFO - Using s3 workspace: /aqua-ml-data as per environment variable SIL_NLP_DATA_PATH.
2023-07-06 12:32:44
ClearML results page: https://app.sil.hosted.allegro.ai/projects/293b4c101f9940d389e894e165898e86/experiments/9009f9764a8b49f991b1cdca405e46b0/output/log
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 141, in <module>
    main()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 125, in main
    exp = SILExperiment(
  File "<string>", line 13, in __init__
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 29, in __post_init__
    self.clearml = SILClearML(self.name, self.clearml_queue)
  File "<string>", line 9, in __init__
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/clearml_connection.py", line 48, in __post_init__
    self._load_config()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/clearml_connection.py", line 96, in _load_config
    SIL_NLP_ENV.copy_experiment_from_bucket(self.name, patterns="config.yml")
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/common/environment.py", line 150, in copy_experiment_from_bucket
    objs = list(data_bucket.object_versions.filter(Prefix=experiment_path + name))
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/boto3/resources/collection.py", line 171, in pages
    for page in pages:
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectVersions operation: The AWS Access Key Id you provided does not exist in our records.
2023-07-06 12:33:00
Process failed, exit code 1
```

**Comment by bhartmoore** [comment]
Via slack from MShannon: 
Update, the AWS credentials were revoked due to a security issue. We are in the process of getting new aws credentials for the AQUA server.

**Comment by bhartmoore** [comment]
Via slack from MShannon:
`New aws credentials have been added to the server to replace the old ones, so everyone should be able to run experiments again`

Experiments are running successfully. Closing this issue.

**Comment by bhartmoore** [comment]
Done.
