### ISSUE TITLE
LookupError: unknown encoding: gb2313

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#230]
The following error occurs when trying to extract CNV:
```
C:\Users\Tim\Documents\git.silnlp\silnlp>poetry run python -m silnlp.common.extract_corpora CNV_2023-11-04
2023-11-12 01:35:14,385 - silnlp.common.environment - INFO - Using workspace: C:\\s3 as per environment variable SIL_NLP_DATA_PATH.
2023-11-12 01:35:14,433 - silnlp.common.extract_corpora - INFO - Extracting CNV_2023-11-04...
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\silnlp\common\extract_corpora.py", line 103, in <module>
    main()
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\silnlp\common\extract_corpora.py", line 77, in main
    corpus_filename, verse_count = extract_project(
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\silnlp\common\paratext.py", line 72, in extract_project
    project_corpus = ParatextTextCorpus(project_dir, include_markers=include_markers)
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\.venv\lib\site-packages\machine\corpora\paratext_text_corpus.py", line 67, in __init__
    texts.append(UsfmFileText(stylesheet, encoding, sfm_filename, versification, include_markers))
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\.venv\lib\site-packages\machine\corpora\usfm_file_text.py", line 21, in __init__
    super().__init__(_get_id(filename, encoding), stylesheet, encoding, versification, include_markers)
  File "C:\Users\Tim\Documents\git.silnlp\silnlp\.venv\lib\site-packages\machine\corpora\usfm_file_text.py", line 30, in _get_id
    with open(filename, "r", encoding=encoding) as file:
LookupError: unknown encoding: gb2313
```

**Comment by ddaspit** [comment]
I believe that this occurring because we are incorrectly mapping the Windows codepage 936 to the Python encoding `gb2313`. It should be mapped to `cp936` or `gbk`.
