### ISSUE TITLE
Experiment command failing during test step - unable to get list of chapters from test books 

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#253]
Running the experiment command with the latest commit to master results in a failure at the start of the test step.  The failure occurs when the test() function is called, but is called without specifying a list of books (which is valid).  When the test() function tries to convert this empty list of books to a list of chapters, it fails:
`    books_nums = get_chapters(";".join(books))
`
A sample experiment with this failure can be seen [here](https://app.sil.hosted.allegro.ai/projects/*/experiments/c60cd607a68c4934b40d6afbd78e6c12/output/log).  This particular experiment does use the `test_books ` option, so running the 'test' command separately may be a workaround, but this should also continue to work for the general `test_size` option.

Detailed stack trace:
```
Training completed
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 141, in <module>
    main()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 137, in main
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 41, in run
    self.test()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 69, in test
    test(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/test.py", line 482, in test
    books_nums = get_chapters(";".join(books))
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/machine/scripture/parse.py", line 167, in get_chapters
    raise ValueError(f"{section} is an invalid book ID.")
ValueError:  is an invalid book ID.
```

**Comment by mmartin9684-sil** [comment]
Unfortunately, the `test` script (and the `train` script) doesn't offer a command line parameter for launching the work on a ClearML queue, so there's no easy workaround for this issue.

**Comment by isaac091** [comment]
Fixed with #254 #255 #256
