### ISSUE TITLE
Handle BOM (Byte-Order Mark) on custom stylesheets

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#338]
I've run across a project with a BOM (0xFFFE) at the start of the custom stylesheet (custom.sty).  This causes the translate command to fail with the stack trace shown below.  It looks like this is another place where we need to handle non-UTF-8 file formats in a Paratext projects.

```
2024-02-28 18:17:16,685 - silnlp.nmt.translate - INFO - Translating XXG ...
2024-02-28 18:17:16,685 - silnlp.nmt.translate - ERROR - Was not able to translate XXG.
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/translate.py", line 116, in translate_books
    translator.translate_book(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/common/translator.py", line 293, in translate_book
    stylesheet = get_stylesheet(src_project_dir, stylesheet_field_update)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/common/translator.py", line 178, in get_stylesheet
    custom_stylesheet = style.parse(file)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/style.py", line 191, in parse
    recs = iter(rec_parser)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/records.py", line 188, in __iter__
    fgs = reduce(accum, fs, [sfm.Element("header")])
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/__init__.py", line 680, in _default_
    for tok in self._tokens:
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/__init__.py", line 304, in __next__
    return self.next()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/__init__.py", line 312, in next
    return next(self._itr)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/__init__.py", line 635, in <genexpr>
    return chain.from_iterable(g if istag else (Text.concat(g),) for istag, g in gs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/__init__.py", line 633, in <genexpr>
    fs = (Text(m.group(), Position(li + 1, m.start() + 1)) for li, ms in lmss for m in ms)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/sfm/style.py", line 181, in <genexpr>
    no_comments = (_comment.sub("", line) for line in source)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.8/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by isaac091** [comment]
The machine.py parser uses `utf-8-sig` when reading project stylesheets and otherwise respects the encoding given in the project's settings file.
