### ISSUE TITLE
Handling "low surrogate" characters in KBTFRA SFM files

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#340]
Extracting the KBTFRA project or running the translate command on SFM files in the KBTFRA project results in 'invalid continuation byte' error messages (see below).

The issue seems to be traceable to the use of 'low surrogate' characters in the project SFM files, as shown in an extract from a _Wildebeest_ character checking report below.  Running the _Wildebeest_ character normalization script over all of the SFM files in the project results in SFM files that can be extracted and translated.  (See S: > Paratext > projects > KBTFRA_norm.)

Stack trace - extract_corpora command:
```
(silnlp-py3.8) PS C:\Users\mm9q\PycharmProjects\silnlp> poetry run python -m silnlp.common.extract_corpora KBTFRA
2024-03-06 08:50:37,595 - silnlp.common.environment - INFO - Using workspace: S:/ as per environment variable SIL_NLP_DATA_PATH.
2024-03-06 08:50:37,825 - silnlp.common.extract_corpora - INFO - Extracting KBTFRA...
Traceback (most recent call last):
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 105, in <module>
    main()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 78, in main
    check_versification(project_dir)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 557, in check_versification
    nt_versification, key_nt_verses = detect_NT_versification(project_dir)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 510, in detect_NT_versification
    jhn_6 = get_last_verse(project_dir, "JHN", 6)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 454, in get_last_verse
    for line in book_file:
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 100: invalid continuation byte
```

Extract of _Wildebeest_ character checking report
```
DETAILS:
Non-canonical character combinations: 0
Character conflict sets: 0
LOW_SURROGATES characters:
    � 0xAB UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCAB) count: 69, lines: 9, 27, 115, 138, 141, 173, 211, 220, 227, 238, 240, 243, 281, 363, 385, 399, 405, 425, 473, 563, 573, 574, 613, 617, 712, 745, 776, 783, 829, 832, 850, 851, 971, 981, 1003, 1017, 1032, 1033, 1050, 1051, 1057, 1087, 1096, 1105, 1107, 1122, 1126, 1165, 1173, 1180, 1202, 1270, 1294, 1312, 1336, 1376, 1429, 1433, 1434, 1449, 1486
    � 0xBB UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCBB) count: 67, lines: 9, 32, 115, 138, 141, 174, 211, 220, 227, 241, 243, 284, 363, 385, 399, 405, 425, 473, 568, 573, 574, 613, 617, 712, 745, 776, 783, 829, 832, 850, 852, 971, 981, 986, 1003, 1017, 1032, 1033, 1050, 1051, 1061, 1087, 1096, 1106, 1107, 1124, 1126, 1173, 1180, 1202, 1270, 1294, 1312, 1336, 1376, 1429, 1433, 1434, 1449, 1486
    � 0xC0 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCC0) count: 13, lines: 122, 133, 174, 319, 533, 608, 973, 978, 1096, 1177, 1224, 1395, 1419
    � 0xC9 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCC9) count: 53, lines: 8, 25, 27, 32, 50, 122, 249, 264, 279, 284, 465, 562, 568, 581, 666, 696, 712, 731, 733, 737, 748, 751, 752, 829, 850, 911, 1003, 1045, 1056, 1094, 1105, 1110, 1187, 1210, 1231, 1234, 1235, 1253, 1270, 1294, 1320, 1356, 1395, 1434, 1452, 1455
    � 0xCA UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCCA) count: 1, line: 9
    � 0xE0 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCE0) count: 421, lines: 8, 10, 13, 15, 18, 40, 47, 51, 55, 59, 74, 77, 93, 97, 102, 103, 108, 114, 122, 130, 131, 133, 134, 141, 143, 152, 153, 157, 158, 170, 171, 174, 180, 183, 184, 193, 194, 195, 198, 201, 207, 208, 209, 211, 212, 226, 230, 236, 240, 248, 256, 261, 266, 268, 269, 278, 293, 294, 314, 319, 320, 328, 333, 336, 339, 349, 352, 354, 363, 369, 375, 376, 383, 385, 389, 391, 396, 405, 412, 415, 423, 427, 428, 434, 442, 446, 449, 453, 454, 470, 472, 473, 475, 478, 484, 494, 499, 500, 503, 504
    � 0xE2 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCE2) count: 28, lines: 93, 230, 269, 474, 587, 599, 863, 934, 970, 971, 973, 975, 978, 1106, 1111, 1216, 1217, 1311, 1319, 1376, 1395, 1399, 1402, 1423, 1429, 1447, 1454
    � 0xE7 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCE7) count: 13, lines: 292, 354, 619, 684, 707, 809, 932, 993, 1018, 1057, 1324, 1376, 1483
    � 0xE8 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCE8) count: 403, lines: 16, 25, 27, 42, 54, 63, 67, 69, 70, 74, 75, 77, 84, 92, 93, 96, 98, 103, 108, 110, 111, 114, 115, 120, 121, 122, 130, 131, 132, 133, 137, 138, 141, 145, 147, 152, 166, 193, 196, 201, 204, 208, 212, 216, 220, 226, 238, 244, 247, 249, 252, 255, 256, 265, 266, 268, 269, 276, 291, 292, 296, 307, 321, 331, 332, 333, 338, 349, 350, 357, 368, 369, 372, 374, 375, 376, 377, 380, 390, 398, 412, 418, 419, 423, 425, 427, 434, 436, 437, 440, 454, 456, 457, 467, 472, 473, 484, 492, 494, 495
    � 0xE9 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCE9) count: 1467, lines: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 24, 25, 28, 31, 36, 38, 42, 43, 44, 47, 48, 50, 51, 54, 55, 56, 59, 61, 63, 64, 69, 70, 71, 74, 75, 77, 79, 81, 84, 85, 86, 88, 89, 92, 93, 94, 96, 97, 98, 99, 102, 107, 110, 111, 114, 115, 117, 118, 120, 121, 122, 125, 127, 130, 132, 133, 134, 135, 137, 138, 139, 140, 141, 142, 147, 149, 152, 153, 155, 157, 159, 161, 162, 163, 166, 169, 170, 171, 173, 174, 175, 178, 182, 184, 186
    � 0xEA UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCEA) count: 150, lines: 7, 8, 9, 13, 35, 36, 41, 44, 59, 63, 65, 75, 99, 108, 110, 131, 137, 187, 199, 204, 217, 234, 235, 307, 313, 321, 328, 333, 343, 350, 352, 456, 470, 477, 482, 487, 490, 493, 512, 559, 568, 571, 573, 577, 582, 591, 594, 605, 683, 712, 717, 720, 729, 766, 795, 807, 811, 821, 825, 828, 849, 876, 894, 897, 911, 926, 937, 938, 939, 950, 1000, 1011, 1029, 1031, 1033, 1048, 1082, 1089, 1096, 1097, 1107, 1111, 1121, 1126, 1132, 1165, 1166, 1168, 1173, 1177, 1200, 1203, 1210, 1212, 1216, 1219, 1225, 1231, 1234, 1235
    � 0xEB UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCEB) count: 9, lines: 8, 133, 314, 1105, 1177, 1187, 1442
    � 0xEE UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCEE) count: 59, lines: 75, 96, 137, 158, 229, 278, 312, 334, 350, 351, 366, 392, 413, 552, 558, 708, 748, 756, 762, 773, 816, 872, 879, 911, 917, 1005, 1013, 1023, 1069, 1087, 1088, 1101, 1109, 1110, 1120, 1128, 1132, 1148, 1157, 1196, 1197, 1210, 1239, 1254, 1265, 1266, 1294, 1311, 1312, 1314, 1329, 1357, 1381, 1440, 1478
    � 0xEF UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCEF) count: 55, lines: 25, 32, 50, 75, 122, 137, 158, 229, 284, 390, 412, 415, 419, 530, 552, 558, 562, 568, 573, 679, 708, 731, 733, 748, 756, 829, 843, 846, 849, 876, 911, 1003, 1005, 1023, 1045, 1069, 1087, 1096, 1101, 1110, 1120, 1128, 1132, 1169, 1187, 1210, 1253, 1311, 1329, 1356, 1381, 1434, 1440
    � 0xF4 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCF4) count: 34, lines: 7, 67, 120, 139, 147, 153, 157, 159, 184, 276, 292, 306, 329, 332, 348, 389, 489, 499, 645, 943, 971, 973, 1045, 1064, 1069, 1151, 1167, 1194, 1376, 1402, 1428, 1434, 1482
    � 0xF9 UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCF9) count: 54, lines: 85, 102, 125, 133, 153, 178, 261, 268, 291, 292, 294, 296, 331, 340, 368, 423, 433, 435, 453, 499, 500, 501, 503, 544, 546, 547, 633, 756, 763, 794, 826, 829, 993, 1020, 1096, 1138, 1173, 1189, 1225, 1234, 1235, 1239, 1240, 1263, 1430, 1433, 1472
    � 0xFB UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCFB) count: 13, lines: 163, 166, 167, 170, 171, 267, 269, 313, 1046, 1096, 1111
    � 0xFC UTF-8 ENCODING ERROR (BYTE SURROGATE: U+DCFC) count: 3, lines: 74, 130, 802
ASCII_PUNCTUATION characters:
```

**Comment by ddaspit** [comment]
This occurs because the code to detect the versification does not respect the encoding setting in the Paratext project settings.
