### ISSUE TITLE
Onboarding App: Error when running alignments 

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/silnlp#405]
Inconsistent error when running alignments:

```Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/mount/src/silnlp/silnlp/nmt/experiment.py", line 197, in <module>

    main()

  File "/mount/src/silnlp/silnlp/nmt/experiment.py", line 178, in main

    exp = SILExperiment(

  File "<string>", line 16, in __init__

  File "/mount/src/silnlp/silnlp/nmt/experiment.py", line 34, in __post_init__

    self.clearml = SILClearML(self.name, self.clearml_queue, commit=self.commit)

  File "<string>", line 10, in __init__

  File "/mount/src/silnlp/silnlp/nmt/clearml_connection.py", line 48, in 

__post_init__

    self._load_config()

  File "/mount/src/silnlp/silnlp/nmt/clearml_connection.py", line 124, in 

_load_config

    self.task.connect(mutable=config, name="config")

  File "/home/adminuser/venv/lib/python3.8/site-packages/clearml/task.py", line 

1438, in connect

    return method(mutable, name=name)

  File "/home/adminuser/venv/lib/python3.8/site-packages/clearml/task.py", line 

3740, in _connect_object

    a_dict = {

  File "/home/adminuser/venv/lib/python3.8/site-packages/clearml/task.py", line 

3743, in <dictcomp>

    for k, v in cls_.__dict__.items()

AttributeError: 'NoneType' object has no attribute '__dict__'```

**Comment by Enkidu93** [comment]
@pandanautinspace Have you seen this error at all?

**Comment by pandanautinspace** [comment]
I believe I have not encountered this error yet

**Comment by Enkidu93** [comment]
@isaac091 The error above seems to be given when the config is completely empty. Could we maybe throw a more descriptive message and catch that earlier on? (Feel free to ping whoever you think should be tackling this).
