### ISSUE TITLE
extract_corpora error about missing start tag that appears to be present caused failing to ignore BOM.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#52]
Having obtained up to date data from a Paratext project I copied it from Windows to a linux machine.
I ran the extract_corpora module and it fails with the following trace:

```david@pop-os:~/silnlp$ python -m silnlp.common.extract_corpora ABP 
2021-06-21 16:29:19,974 - silnlp - ERROR - The .Net Core SDK needs to be installed (https://dotnet.microsoft.com/download) to be able to use the functionality in sil.machine.tool (most of silnlp).
2021-06-21 16:29:20,396 - silnlp.common.extract_corpora - INFO - Extracting ABP...
2021-06-21 16:29:21,120 - silnlp.common.paratext - INFO - # of Segments: 31104
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/david/silnlp/silnlp/common/extract_corpora.py", line 70, in <module>
    main()
  File "/home/david/silnlp/silnlp/common/extract_corpora.py", line 58, in main
    extract_term_renderings(project)
  File "/home/david/silnlp/silnlp/common/paratext.py", line 200, in extract_term_renderings
    extract_terms_list(list_type, project_folder)
  File "/home/david/silnlp/silnlp/common/paratext.py", line 137, in extract_terms_list
    terms_tree = etree.parse(str(terms_xml_path), parser=parser_utf8)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/david/disk2/gutenberg/Paratext/projects/ABP/ProjectBiblicalTerms.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
david@pop-os:~/silnlp$ 
```

I tried using `dos2unix -r -ascii TermRenderings.xml` to remove the BOM and convert line endings. extract_corpora gave the same error.

I opened TermRenderings.xml in a text editor and saved it with the same name. Line 1 column 1 appears to be a start tag '<'.
Saving and running extract_corpora gave the same error.

**Comment by ddaspit** [comment]
@davidbaines Have you uploaded the project data to Gutenberg? I would like to try to reproduce this error.

**Comment by davidbaines** [comment]
Project data should be in the projects folders ABP_2021_06_22 and ABPBTE_2021_06_22.

**Comment by davidbaines** [comment]
I've just tried this again and found that the problem is the BOM at the beginning of the file.  Here's some information about the file and showing just the first few bytes shows the problem. 

```david@pop-os:~/silnlp$ head -c 8 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
<?xmldavid@pop-os:~/silnlp$ head -c 1 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
�david@pop-os:~/silnlp$ head -c 2 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
�david@pop-os:~/silnlp$ head -c 3 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
david@pop-os:~/silnlp$ head -c 4 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
<david@pop-os:~/silnlp$ file /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
/home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml: XML 1.0 document, UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators``` 

I tried `dos2unix -r`  without the -ascii flag and that appears to have solved the problem.
```david@pop-os:~/silnlp$ dos2unix -r /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
dos2unix: converting file /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml to Unix format...
david@pop-os:~/silnlp$ head -c 4 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
<?xmdavid@pop-os:~/silnhead -c 1 /home/david/disk2/gutenberg/Paratext/projects/ABP_2021_06_22/TermRenderings.xml
<david@pop-os:~/silnlp$```

After removing the BOM from all the xml files then the extract_corpora worked.

```david@pop-os:~/silnlp$ python -m silnlp.common.extract_corpora ABP_2021_06_22
2021-06-25 10:35:14,398 - silnlp.common.extract_corpora - INFO - Extracting ABP_2021_06_22...
2021-06-25 10:35:15,110 - silnlp.common.paratext - INFO - # of Segments: 31104
2021-06-25 10:35:15,270 - silnlp.common.paratext - INFO - # of Terms: 1307
2021-06-25 10:35:15,285 - silnlp.common.extract_corpora - INFO - Done.
```

**Comment by davidbaines** [comment]
So is it possible to reliably detect and remove a BOM?

**Comment by johnml1135** [comment]
BOM = "Byte Order Mark"

**Comment by davidbaines** [comment]
For an example of a project folder where the xml files have a BOM see gutenberg/Paratext/projects/ABP_2021_06_22_BOM

**Comment by johnml1135** [comment]
Related issues:
* https://bugs.launchpad.net/lxml/+bug/1842387
* https://stackoverflow.com/questions/50970691/lxml-lookuperror-occured-arguments-unknown-encoding-butf-8-sig
