### ISSUE TITLE
Error returned: Unhandled exception. System.DllNotFoundException: Unable to load DLL 'thot' or one of its dependencies:

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#61]
I received this error when trying to run the unit tests on a new computer:

```
RuntimeError: Error in executing: dotnet machine train alignment-model C:\Users\johnm\AppData\Local\Temp\tmp69nxi0fv\ C:\Users\johnm\AppData\Local\Temp\tmp69nxi0fv\src.txt C:\Users\johnm\AppData\Local\Temp\tmp69nxi0fv\trg.txt -mt fast_align -l
Error returned: Unhandled exception. System.DllNotFoundException: Unable to load DLL 'thot' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SIL.Machine.Translation.Thot.Thot.swAlignModel_create(String className)
   at SIL.Machine.Translation.Thot.ThotWordAlignmentModelTrainer`1..ctor(String prefFileName, ITokenProcessor sourcePreprocessor, ITokenProcessor targetPreprocessor, ParallelTextCorpus corpus, Int32 maxCorpusCount) in C:\projects\machine\src\SIL.Machine.Translation.Thot\ThotWordAlignmentModelTrainer.cs:line 38
   at SIL.Machine.AlignmentModelCommandSpec.CreateThotAlignmentModelTrainer[TAlignModel](ParallelTextCorpus corpus, Int32 maxSize, ITokenProcessor processor, Dictionary`2 parameters, Boolean direct) in C:\projects\machine\src\SIL.Machine.Tool\AlignmentModelCommandSpec.cs:line 152
   at SIL.Machine.AlignmentModelCommandSpec.CreateAlignmentModelTrainer(ParallelTextCorpus corpus, Int32 maxSize, ITokenProcessor processor, Dictionary`2 parameters, Boolean direct) in C:\projects\machine\src\SIL.Machine.Tool\AlignmentModelCommandSpec.cs:line 115
   at SIL.Machine.TrainAlignmentModelCommand.ExecuteCommandAsync(CancellationToken ct) in C:\projects\machine\src\SIL.Machine.Tool\TrainAlignmentModelCommand.cs:line 75
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at SIL.Machine.Program.<Main>(String[] args)
exp_folder = WindowsPath('c:/Users/johnm/Documents/repos/silnlp/tests/MT/Experiment_Truth/es-ULB')
...
```

What could be causing it?

**Comment by johnml1135** [comment]
I figured it out.  dotnet machine needs the C++ redistributable.  I needed to install it from here: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0.

Does this normally get installed or do we need to update instructions in the readme?

**Comment by ddaspit** [comment]
I think that this is usually installed, but we should probably update the README, since it is possible that it might not be installed.

**Comment by johnml1135** [comment]
Done.
