### ISSUE TITLE
No module named 'machine.translation'

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#84]
Currently I'm unable to use the repo because many commands lead to a module not found error. It may be caused by a configuration issue on my machine and perhaps not an issue with the code itself. 
The repo is up to date. 

Here's a sample error. There is a similar error when trying to preprocess.

```D:\GitHub\silnlp>python -m silnlp.nmt.config --src this --trg that other en-many-test
2021-10-12 16:14:00.024315: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\GitHub\silnlp\silnlp\nmt\config.py", line 25, in <module>
    from ..alignment.machine_aligner import FastAlignMachineAligner
  File "D:\GitHub\silnlp\silnlp\alignment\machine_aligner.py", line 14, in <module>
    from machine.translation import (
ModuleNotFoundError: No module named 'machine.translation'
```

  silnlp.common.extract_corpora is working fine.

**Comment by ddaspit** [comment]
This sounds like the Machin library is not installed. Have you tried running `poetry install`?

**Comment by ddaspit** [comment]
@davidbaines Did you get this working?
